### ISSUE TITLE
table order isn't preserved when a query is present

### ISSUE THREAD

**Issue by oganm** [PavlidisLab/GemBrow#112]
If query is filled, ordering by the columns of the table does not correctly sort the results

Lack of order
![image](https://github.com/user-attachments/assets/6321d9a7-832b-4d6e-9a3e-908ccb81a4ea)

Order
![image](https://github.com/user-attachments/assets/761d20b8-18c0-40b6-88be-808da183f63c)

**Comment by arteymix** [comment]
It's possible that the order is ignored in the backend because we sort results by full text score. I'll take a look!

**Comment by arteymix** [comment]
So yes, I just checked the code and this actually a bit more fancy: results are sorted first by FT score and then by whatever column you picked. I guess we can change that, but we need a way to sort by score by default. I think right now the frontend by `-id` by default.

**Comment by arteymix** [comment]
Fixed in https://github.com/PavlidisLab/Gemma/commit/9357bd8ee5b7438b4db29e72d80d47d04141973e.

New behavior: sort is now has two possible defaults: if a query is set, `-searchResult.score` otherwise it's `+id`.

You can explicitly sort by `-searchResult.score` and even `+searchResult.score`. However, for that to work, you must pass the `query` parameter.
