### ISSUE TITLE
No filter is generated for a free text term

### ISSUE THREAD

**Issue by arteymix** [PavlidisLab/GemBrow#71]
I just got a browser error on checking an annotation box

[Slack Message](https://pavlidis-lab.slack.com/archives/C40S0SE4V/p1694542257509389)

Discovered by @ppavlidis

**Comment by libby-natola** [comment]
Hey Guillaume, did you already sort this error? I was able to recreate it a couple days ago but now AIN93G is not an option in any category.

**Comment by libby-natola** [comment]
Nevermind I was able to pull it up with a taxon filter. So I think I see what the problem is, there is no termUri being added to the filter because there is no termUri associated with this termName. Did you want the solution to this to be to not show termNames with no termUri in the treeview in the first place? Or did you want me to try to get the box to function without a termUri?

**Comment by libby-natola** [comment]
commit 2a7cfef787508694dae6ae79e4ebd0a7f5fa89e9
