### ISSUE TITLE
High-level category counts do not respond to filters

### ISSUE THREAD

**Issue by ppavlidis** [PavlidisLab/GemBrow#88]
Example:

<img width="370" alt="image" src="https://github.com/PavlidisLab/GemBrow/assets/206415/7ffebfff-0330-4e99-ad0a-ead3b7683c20">

The value next to Disease for example, should be something like the total number of experiments selected, in response to the "Ammon's horn" filter?

**Comment by arteymix** [comment]
Good question.

Categories used to be selectable, so the count would reflect the number of datasets if the category would be selected. Thus the count by applying every other filter (taxa, other categories, ...).

I guess we could change that behaviour to instead reflect the number of datasets in the selection. I feel however that it would be a little useless since that information is already provided by the selection.

**Comment by arteymix** [comment]
Also, the counts are not visible in production and categories are not selectable. This is the correct behaviour.

**Comment by arteymix** [comment]
Oh, I got confused there. The disease count does not reflect the selection in organism parts. This is either a bug or an incomplete feature. Let me check.

**Comment by arteymix** [comment]
I looked up the code. The counts per category only reflect taxa and platform filters. Filters from other categories are simply ignored.

**Comment by ppavlidis** [comment]
Since this is only apparent in the debug mode, which I didn't realize, this isn't really an issue.
